//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gas_Flow_Control_Manager.Acsess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameters
    {
        public int Id { get; set; }
        public Nullable<int> GasCompressorId { get; set; }
        public string ParameterName { get; set; }
        public Nullable<decimal> ParameterValue { get; set; }
    
        public virtual GasCompressors GasCompressors { get; set; }
    }
}
