//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasFlowControlManager.Acsess.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasCompressors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GasCompressors()
        {
            this.Parameters = new HashSet<Parameters>();
            this.States = new HashSet<States>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<decimal> MaxPressure { get; set; }
        public Nullable<decimal> MaxFlowRate { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<decimal> CurrentFlowRate { get; set; }
        public Nullable<decimal> CurrentPressure { get; set; }
        public Nullable<decimal> CurrentEfficiency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parameters> Parameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<States> States { get; set; }
    }
}
