//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasFlowControlManager.Acsess.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameters
    {
        public int Id { get; set; }
        public Nullable<int> GasCompressorId { get; set; }
        public string ParameterName { get; set; }
        public Nullable<decimal> ParameterValue { get; set; }
    
        public virtual GasCompressors GasCompressors { get; set; }
    }
}
